# Generated by Django 4.1 on 2022-09-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCandyRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='madio_de_pago',
            new_name='medio_de_pago',
        ),
    ]
